name: Build Platform

on:
  schedule:
    - cron: "0 22 * * *"
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish a stable build"
        required: true
        type: boolean

jobs:
  build:
    runs-on: ${{ matrix.arch == 'aarch64' && 'ARM64' || 'ubuntu-latest' }}
    container:
      image: ghcr.io/tau-os/builder:nightly
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flathub
        run: |
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
      - name: Install GNOME platform
        run: flatpak install -y --noninteractive flathub org.gnome.Platform//44 org.gnome.Sdk//44
      - name: Flatpak build
        uses: tau-OS/flatpak-github-actions/flatpak-builder@master
        with:
          build-bundle: false
          manifest-path: com.fyralabs.Sdk.json
          arch: ${{ matrix.arch }}
          branch: ${{ inputs.publish && 'stable' || 'nightly' }}
          cache: true
      - name: Upload
        uses: tau-OS/flatpak-github-actions/flat-manager@master
        with:
          repository: ${{ inputs.publish && 'stable' || 'unstable' }}
          flat-manager-url: https://manager.flatpak.fyralabs.com/
          token: ${{ secrets.FLATPAK_REPO_TOKEN }}
