name: Build Platform

on:
  schedule:
    - cron: "0 22 * * *"
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish a stable build"
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          dnf -y install nodejs docker flatpak
      - name: Set up QEMU
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Flatpak build
        uses: flatpak/flatpak-github-actions@v2
        with:
          build-bundle: false
          manifest-path: com.fyralabs.Sdk.json
          arch: ${{ matrix.arch }}
          branch: ${{ inputs.publish && 'stable' || 'nightly' }}
          cache: false

      - name: Upload
        uses: flatpak/flatpak-github-actions@v2
        with:
          repository: ${{ inputs.publish && 'stable' || 'unstable' }}
          flat-manager-url: https://manager.flatpak.fyralabs.com/
          token: ${{ secrets.FLATPAK_REPO_TOKEN }}
