name: Build Platform

on:
  schedule:
    - cron: "0 22 * * *"
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish a stable build"
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-43
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          dnf -y install nodejs docker flatpak
      - name: Set up QEMU
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Flatpak build
        uses: tau-OS/flatpak-github-actions/flatpak-builder@master
        with:
          bundle: out.flatpak
          manifest-path: co.tauos.Sdk.json
          arch: ${{ matrix.arch }}
          branch: ${{ inputs.publish == 'true' && 'stable' || 'daily' }}
          cache-key: flatpak-builder-${{ github.sha }}-${{ matrix.arch }}

      - name: Upload
        uses: tau-OS/flatpak-github-actions/flat-manager@master
        with:
          repository: unstable
          flat-manager-url: https://catalogue.tauos.co/
          token: ${{ secrets.FLATPAK_REPO_TOKEN }}
